apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
    taints: []
    criSocket: /var/run/crio/crio.sock
    kubeletExtraArgs:
        node-ip: 192.168.110.5
localAPIEndpoint:
    advertiseAddress: 192.168.110.5
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
# Allowing for CPU pinning and isolation in case of guaranteed QoS class
cpuManagerPolicy: static
systemReserved:
    cpu: 500m
    memory: 256M
kubeReserved:
    cpu: 500m
    memory: 256M
topologyManagerPolicy: best-effort
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
networking:
    dnsDomain: cluster.local
    podSubnet: 10.244.0.0/16
    serviceSubnet: 10.96.0.0/16
controlPlaneEndpoint: "192.168.110.5:6443"
apiServer:
    certSANs:
    - 192.168.110.5
    extraArgs:
        advertise-address: 192.168.110.5

