apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inframanager-cluster-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: inframanager-cluster-role-binding
roleRef:
  kind: ClusterRole
  name: inframanager-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: inframanager-sa
    namespace: kube-system
