apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infraagent-cluster-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "services", "endpoints", "configmaps", "networkpolicies", "pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infraagent-cluster-role-binding
roleRef:
  kind: ClusterRole
  name: infraagent-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: infraagent-sa
    namespace: kube-system
